[project]
name = "tradutor"
version = "0.3.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argostranslate>=1.11.0",
    "beautifulsoup4>=4.15.0",
    "ebooklib>=0.20",
    "layoutparser>=0.3.4",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "pymupdf>=1.28.2",
    "pytesseract>=0.3.13",
]

[project.scripts]
tradutor = "tradutor:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
